apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: rbalajee/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: "src/**/*.js"
          - dest: .
            src: "src/**/*.css"
          - dest: .
            src: "src/**/*.html"
    - image: rbalajee/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - dest: .
            src: "src/**/*.js"
    - image: rbalajee/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - dest: .
            src: "src/**/*.js"
deploy:
  kubectl:
    manifests:
      - ./k8s/*
      - ./k8s-dev/*
